// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Household struct {
	HouseholdID   pgtype.UUID        `json:"household_id"`
	HouseholdName string             `json:"household_name"`
	Address       pgtype.Text        `json:"address"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Inventory struct {
	ItemID         pgtype.UUID        `json:"item_id"`
	HouseholdID    pgtype.UUID        `json:"household_id"`
	Category       string             `json:"category"`
	Name           string             `json:"name"`
	Quantity       int32              `json:"quantity"`
	ExpirationDate pgtype.Date        `json:"expiration_date"`
	PurchaseDate   pgtype.Date        `json:"purchase_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Location       pgtype.Text        `json:"location"`
}

type Recipe struct {
	ID         pgtype.UUID        `json:"id"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	Visibility int32              `json:"visibility"`
	Data       []byte             `json:"data"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	UserID       pgtype.UUID        `json:"user_id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	FirstName    string             `json:"first_name"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	HouseholdID  pgtype.UUID        `json:"household_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
