// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error)
	CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (Inventory, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteHousehold(ctx context.Context, householdID pgtype.UUID) (Household, error)
	DeleteInventoryItem(ctx context.Context, itemID pgtype.UUID) (Inventory, error)
	DeleteRecipe(ctx context.Context, id pgtype.UUID) (Recipe, error)
	DeleteUser(ctx context.Context, email string) (User, error)
	FetchHousehold(ctx context.Context, householdID pgtype.UUID) (Household, error)
	FetchInventoryItem(ctx context.Context, itemID pgtype.UUID) (Inventory, error)
	FetchRecipe(ctx context.Context, id pgtype.UUID) (Recipe, error)
	FetchUserByEmail(ctx context.Context, email string) (User, error)
	FetchUserByUserId(ctx context.Context, userID pgtype.UUID) (User, error)
	FetchUserByUserName(ctx context.Context, username string) (User, error)
	ListHouseholdMembers(ctx context.Context, arg ListHouseholdMembersParams) ([]User, error)
	ListHouseholds(ctx context.Context, arg ListHouseholdsParams) ([]Household, error)
	ListInventoryItems(ctx context.Context, arg ListInventoryItemsParams) ([]Inventory, error)
	ListInventoryItemsByCategory(ctx context.Context, arg ListInventoryItemsByCategoryParams) ([]Inventory, error)
	ListInventoryItemsByLocation(ctx context.Context, arg ListInventoryItemsByLocationParams) ([]Inventory, error)
	ListRecipes(ctx context.Context, arg ListRecipesParams) ([]Recipe, error)
	ListRecipesByAuthor(ctx context.Context, arg ListRecipesByAuthorParams) ([]Recipe, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error)
	UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (Inventory, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
